version: '3'

networks:
  api-connection:
    driver: bridge
  db-connection:
    driver: bridge
  redis-connection:
    driver: bridge

services:
  redis:
    container_name: redis
    restart: always
    image: 'redis'
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  api:
    image: noah071610/test-app-with-actions
    container_name: test-app-with-actions-container
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    expose:
      - '3000'
    networks:
      - db-connection
      - redis-connection
      - api-connection
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - db-connection
      - redis-connection
      - api-connection
    depends_on:
      - db
      - redis
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
