name: Docker Image CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    environment: mytest # 아.... ㅡㅡ 이제 이해됨
    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t test-app-with-actions .

      - name: tagging
        run: docker tag test-app-with-actions:latest noah071610/test-app-with-actions:latest

      - name: Push to Dockerhub
        run: docker push noah071610/test-app-with-actions:latest
