name: Docker Image CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Environment Variable
        # Step에 Environment Variable 선언
        env:
          STEP_ENV: step_environment_variable
        run: |
          echo Workflow Environment Variable : $WORKFLOW_ENV
          echo Job Environment Variable $JOB_ENV
          echo Step Environment Variable $STEP_ENV
      - uses: actions/checkout@v3
      - name: ECHO
        env:
          DOCKER_USERNAME: ${{ secrets.ECHO_HELLO_WORLD }}
          # DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: echo $ECHO_HELLO_WORLD
      - name: Test 2
        env:
          DOCKER_USERNAME_2: ${{ secrets.ECHO_HELLO_WORLD_2 }}
        run: echo $DOCKER_USERNAME_2
      # - name: Login Dockerhub
      #   env:
      #     DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      #     DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      #   run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      # - name: Build the Docker image
      #   run: docker build -t manaweb-api .
      # - name: tagging
      #   run: docker tag manaweb-api:latest mag123c/manaweb-api:latest
      # - name: Push to Dockerhub
      #   run: docker push mag123c/manaweb-api:latest
